[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.zip", "php83Extensions.mbstring", "php83Extensions.gd", "php83Extensions.curl", "php83Extensions.openssl", "php83Extensions.session", "php83Extensions.json", "composer"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
